### ISSUE TITLE
Question about potential use case: memoisation of simple calculation

### ISSUE THREAD

**Issue by AlexMikhalev** [ozgrakkurt/sbbf-rs#9]
I was wondering if sbbf can be used to check and memoize calculation:
```
    /// Combining two numbers into a unique one: pairing functions.
    /// It uses "elegant pairing" (https://odino.org/combining-two-numbers-into-a-unique-one-pairing-functions/).
    fn magic_pair(a: u32, b: u32) -> u64 {
        let x = u64::from(a);
        let y = u64::from(b);
        if x >= y {
            x * x + x + y
        } else {
            y * y + x
        }
    }
```

**Comment by AlexMikhalev** [comment]
I have a stream of pairs and I would like to build a sparse matrix out of it, I am checking if it's worth plugging SBBF, do I need to have a whole dataset before building filter like in bloom?
Code is taken from https://github.com/BaseModelAI/cleora/blob/master/src/sparse_matrix.rs and my example is graph embeddings.

**Comment by ozgrakkurt** [comment]
> I have a stream of pairs and I would like to build a sparse matrix out of it, I am checking if it's worth plugging SBBF, do I need to have a whole dataset before building filter like in bloom? Code is taken from https://github.com/BaseModelAI/cleora/blob/master/src/sparse_matrix.rs and my example is graph embeddings.

If you have all of the data set you can build something like [this](https://hhoppe.com/perfecthash.pdf?from=https://research.microsoft.com/en-us/um/people/hoppe/perfecthash.pdf&type=path) which should be better than bloom filters. I think there are implementations for this in rust as well.

But if you know approximately how many unique ones you will have, and don't have all of them at the time of building the filter, bloom filter is good.

If you don't have an approximation how many there will be, there are scalable filters I think.

I see the linked impl uses a hashmap so putting bloom filter in front of it won't have a big impact I think.

Maybe it is possible to replace this hashmap with bloom filter?

You could put `magic_pair` outputs into bloom filter in order to determine if this pair is already in the matrix I think.

If this structure will be immutable in the end, the best  way might be to construct it with simple implementation and then put it into spatial perfect hash structure.

Also `BTreeMap` is better at space usage than `HashMap`, also I think `wyhash` is better than `FxHash` .

In terms of speed, rust HashMap is very fast if you use it with a good hash function instead of the default one, so bloom filter + vector instead of hashmap won't be better I think.

**Comment by AlexMikhalev** [comment]
Great, thank you. I will stick with hashmap for now.

**Comment by AlexMikhalev** [comment]
test wyhash_bench::hash_1_mega_bytes ... bench:      67,839 ns/iter (+/- 623) = 15456 MB/s 

you are right, wyhash is faster on cleore benchmark.
